### ISSUE TITLE
Documentation needs review.

### ISSUE THREAD

**Issue by jselmani** [jselmani/Extractor#5]
To ensure that this project can be used by others without confusion, I would like it be reviewed for both technical correctness and user readability (is it easy to comprehend).

Thank you, and kindly leave a comment if you would like to review the project.

**Comment by ericschv** [comment]
Hi Jiel, I would like to review your project.

**Comment by jselmani** [comment]
@ericschv great! Let me know when you are finished and feel free to make changes and push back.
